import { prisma } from '../src/prisma/client';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';

dotenv.config();

async function analyzeUnmatched() {
  console.log('🔍 Analyzing unmatched products and images...\n');
  
  // Load images
  const jsonPath = path.resolve(__dirname, '../all-images-list.json');
  const jsonData = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  const allImages = jsonData.cloudinary?.all || [];
  
  // Get all products
  const products = await prisma.product.findMany({
    select: {
      id: true,
      name: true,
      category: {
        select: { name: true },
      },
    },
  });
  
  // Get products with images
  const productsWithImages = await prisma.productImage.findMany({
    select: {
      product_id: true,
      image: true,
    },
  });
  
  const productsWithImageIds = new Set(productsWithImages.map(pi => pi.product_id));
  const unmatchedProducts = products.filter(p => !productsWithImageIds.has(p.id));
  
  console.log(`📦 Total products: ${products.length}`);
  console.log(`✅ Products with images: ${productsWithImageIds.size}`);
  console.log(`❌ Products without images: ${unmatchedProducts.length}\n`);
  
  interface ImageInfo {
    name: string;
    url: string;
    uploadedAt?: string;
  }
  
  // Check which images are auto-generated
  const autoGeneratedImages = allImages.filter((img: ImageInfo) => {
    const imageName = img.name.split('/').pop() || '';
    // Auto-generated: random alphanumeric strings, typically in products/ folder
    return imageName.length > 15 && /^[a-z0-9]+$/i.test(imageName) && !imageName.includes('_');
  });
  
  console.log(`🖼️  Total images: ${allImages.length}`);
  console.log(`🤖 Auto-generated images: ${autoGeneratedImages.length}`);
  console.log(`📝 Named images: ${allImages.length - autoGeneratedImages.length}\n`);
  
  // Check which auto-generated images are already used
  const usedImageUrls = new Set(productsWithImages.map(pi => pi.image));
  const unusedAutoGenerated = autoGeneratedImages.filter((img: ImageInfo) => !usedImageUrls.has(img.url));
  
  console.log(`🔄 Unused auto-generated images: ${unusedAutoGenerated.length}\n`);
  
  if (unmatchedProducts.length > 0 && unusedAutoGenerated.length > 0) {
    console.log('📋 Matching strategy: Sequential 1:1 matching\n');
    console.log(`   Products to match: ${unmatchedProducts.length}`);
    console.log(`   Images available: ${unusedAutoGenerated.length}`);
    console.log(`   Can match: ${Math.min(unmatchedProducts.length, unusedAutoGenerated.length)}\n`);
  }
  
  await prisma.$disconnect();
}

analyzeUnmatched().catch(console.error);
