import { prisma } from '../src/prisma/client';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';

dotenv.config();

interface ImageInfo {
  name: string;
  url: string;
  size?: number;
  format?: string;
  folder?: string;
  uploadedAt?: string;
}

// Helper to normalize product names for matching
function normalizeName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_and_/g, '_')
    .replace(/_w_o_/g, '_without_')
    .replace(/_w_o/g, '_without');
}

// Check if image name looks auto-generated (random characters)
function isAutoGenerated(name: string): boolean {
  const parts = name.split('/');
  const fileName = parts[parts.length - 1];
  // Auto-generated names are typically random alphanumeric strings
  // Check if it's mostly random characters (not meaningful words)
  const hasWords = /[a-z]{3,}/.test(fileName.toLowerCase());
  return !hasWords || fileName.length > 20;
}

async function matchAutoGeneratedImages() {
  console.log('🚀 Matching auto-generated images to products...\n');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  
  // Load images from JSON
  const jsonPath = path.resolve(__dirname, '../all-images-list.json');
  if (!fs.existsSync(jsonPath)) {
    console.error(`❌ JSON file not found: ${jsonPath}`);
    process.exit(1);
  }
  
  const jsonData = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  const allImages: ImageInfo[] = jsonData.cloudinary?.all || [];
  
  console.log(`📸 Loaded ${allImages.length} images from JSON\n`);
  
  // Get all products from database
  const products = await prisma.product.findMany({
    select: {
      id: true,
      name: true,
      category: {
        select: {
          name: true,
        },
      },
    },
    orderBy: {
      name: 'asc',
    },
  });
  
  console.log(`📦 Found ${products.length} products in database\n`);
  
  // Get products that already have images
  const productsWithImages = await prisma.productImage.findMany({
    select: {
      product_id: true,
    },
  });
  
  const productsWithImageIds = new Set(productsWithImages.map(pi => pi.product_id));
  
  // Filter to unmatched products
  const unmatchedProducts = products.filter(p => !productsWithImageIds.has(p.id));
  
  console.log(`🔍 Found ${unmatchedProducts.length} products without images\n`);
  
  // Filter to auto-generated images (those not yet matched)
  const autoGeneratedImages = allImages.filter(img => {
    const imageName = img.name.split('/').pop() || '';
    return isAutoGenerated(imageName);
  });
  
  console.log(`🖼️  Found ${autoGeneratedImages.length} auto-generated images\n`);
  
  // Sort images by upload date (most recent first, as they're likely the new uploads)
  autoGeneratedImages.sort((a, b) => {
    const dateA = a.uploadedAt ? new Date(a.uploadedAt).getTime() : 0;
    const dateB = b.uploadedAt ? new Date(b.uploadedAt).getTime() : 0;
    return dateB - dateA;
  });
  
  // Sort products by importance (you can customize this logic)
  // For now, let's prioritize products that don't have images yet
  const sortedProducts = [...unmatchedProducts];
  
  console.log('🔄 Matching auto-generated images to products...\n');
  console.log('📋 Strategy: Matching images to products in order of upload date\n');
  
  const matches: Array<{ productId: string; productName: string; imageUrl: string; imageName: string }> = [];
  const usedImageUrls = new Set<string>();
  const usedProductIds = new Set<string>();
  
  // Match images to products 1:1
  // Since we can't "see" the images, we'll match them sequentially
  // This assumes images were uploaded in roughly the same order as products
  let imageIndex = 0;
  
  for (const product of sortedProducts) {
    if (imageIndex >= autoGeneratedImages.length) {
      break; // No more images to match
    }
    
    const image = autoGeneratedImages[imageIndex];
    
    if (!usedImageUrls.has(image.url) && !usedProductIds.has(product.id)) {
      matches.push({
        productId: product.id,
        productName: product.name,
        imageUrl: image.url,
        imageName: image.name,
      });
      
      usedImageUrls.add(image.url);
      usedProductIds.add(product.id);
      
      console.log(`✅ [${matches.length}/${Math.min(sortedProducts.length, autoGeneratedImages.length)}] ${product.name} → ${image.name.split('/').pop()}`);
      
      imageIndex++;
    }
  }
  
  console.log(`\n📊 Matched ${matches.length} products with auto-generated images\n`);
  
  if (matches.length === 0) {
    console.log('⚠️  No matches found. Exiting.');
    await prisma.$disconnect();
    return;
  }
  
  // Update database
  console.log('💾 Updating database...\n');
  
  let updated = 0;
  let created = 0;
  let failed = 0;
  
  for (const match of matches) {
    try {
      // Check if product already has an image
      const existingImage = await prisma.productImage.findFirst({
        where: { product_id: match.productId },
      });
      
      if (existingImage) {
        await prisma.productImage.update({
          where: { id: existingImage.id },
          data: {
            image: match.imageUrl,
            status: 'COMPLETE',
            is_active: true,
          },
        });
        updated++;
      } else {
        await prisma.productImage.create({
          data: {
            product_id: match.productId,
            image: match.imageUrl,
            status: 'COMPLETE',
            is_active: true,
          },
        });
        created++;
      }
      
      // Update product has_images flag
      await prisma.product.update({
        where: { id: match.productId },
        data: { has_images: true },
      });
    } catch (error) {
      failed++;
      console.error(`❌ Failed to update ${match.productName}: ${(error as Error).message}`);
    }
  }
  
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('📊 SUMMARY:');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`   ✅ Updated: ${updated} products`);
  console.log(`   ➕ Created: ${created} products`);
  console.log(`   ❌ Failed: ${failed} products`);
  console.log(`   📈 Total matched: ${matches.length} products`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  
  // Save matches to file for review
  const matchesPath = path.resolve(__dirname, '../auto-generated-image-matches.json');
  fs.writeFileSync(matchesPath, JSON.stringify({
    generatedAt: new Date().toISOString(),
    totalMatches: matches.length,
    matches: matches,
  }, null, 2));
  
  console.log(`💾 Matches saved to: ${matchesPath}\n`);
  console.log('✅ Auto-generated image matching completed!\n');
  
  await prisma.$disconnect();
}

matchAutoGeneratedImages().catch((error) => {
  console.error('❌ Fatal error:', error);
  process.exit(1);
});
