import { prisma } from '../src/prisma/client';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';

dotenv.config();

interface ProductInput {
  name: string;
  category: string;
  price?: number | string;
  selling_price?: number | string;
  quantity?: number;
  unit: string;
  image?: string;
}

interface ImageInfo {
  name: string;
  url: string;
  uploadedAt?: string;
  format?: string;
}

async function recreateAndMatchManualImages() {
  console.log('🔄 Recreating Products and Matching Manual Images...\n');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  
  // Step 1: Recreate products from seed files
  console.log('📦 Step 1: Recreating Products from Seed Files...\n');
  
  const seedFiles = [
    {
      name: 'Dates',
      file: path.resolve(__dirname, '../seeder_with_images/dates-products.json'),
    },
    {
      name: 'Dried Fruits & Nuts',
      file: path.resolve(__dirname, '../seeder_with_images/dried-fruits-nuts-products.json'),
    },
    {
      name: 'Grains, Pulses & Rice',
      file: path.resolve(__dirname, '../seeder_with_images/grains_pulses_rice.json'),
    },
    {
      name: 'Spices',
      file: path.resolve(__dirname, '../image-seeder/spices_products.json'),
    },
  ];
  
  const allProducts: Array<{ product: ProductInput; category: string }> = [];
  
  for (const seed of seedFiles) {
    if (!fs.existsSync(seed.file)) {
      console.log(`   ⚠️  File not found: ${seed.file}`);
      continue;
    }
    
    const data = JSON.parse(fs.readFileSync(seed.file, 'utf-8'));
    const products = Array.isArray(data) ? data : [];
    
    products.forEach((p: ProductInput) => {
      allProducts.push({
        product: p,
        category: seed.name,
      });
    });
    
    console.log(`   ✅ Loaded ${products.length} products from ${seed.name}`);
  }
  
  console.log(`\n   Total products to create: ${allProducts.length}\n`);
  
  // Step 2: Load manually uploaded images from February/March
  console.log('📸 Step 2: Loading Manually Uploaded Images...\n');
  
  const jsonPath = path.resolve(__dirname, '../all-cloudinary-images-complete.json');
  if (!fs.existsSync(jsonPath)) {
    console.error('❌ Image list file not found:', jsonPath);
    process.exit(1);
  }
  
  const jsonData = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  const allImages: ImageInfo[] = jsonData.all || jsonData.images || [];
  
  // Filter to February and March, and exclude named images (keep only auto-generated/manual uploads)
  const manualImages: ImageInfo[] = [];
  
  for (const img of allImages) {
    if (!img.uploadedAt) continue;
    
    const uploadDate = new Date(img.uploadedAt);
    const year = uploadDate.getFullYear();
    const month = uploadDate.getMonth() + 1;
    
    if (year === 2026 && (month === 2 || month === 3)) {
      const fileName = img.name.split('/').pop() || '';
      // Check if it's an auto-generated name (random characters, not a product name)
      const isAutoGenerated = fileName.length > 15 && /^[a-z0-9]+$/i.test(fileName) && !fileName.includes('_');
      const isNamedProduct = fileName.includes('_') && !fileName.match(/^[a-z0-9]{15,}$/i);
      
      // Include auto-generated and some manual uploads
      if (isAutoGenerated || (!isNamedProduct && fileName.length > 10)) {
        manualImages.push(img);
      }
    }
  }
  
  // Sort by upload date
  manualImages.sort((a, b) => {
    const dateA = a.uploadedAt ? new Date(a.uploadedAt).getTime() : 0;
    const dateB = b.uploadedAt ? new Date(b.uploadedAt).getTime() : 0;
    return dateA - dateB; // Oldest first
  });
  
  console.log(`   ✅ Found ${manualImages.length} manually uploaded images\n`);
  
  // Step 3: Create categories and products
  console.log('🏗️  Step 3: Creating Categories and Products...\n');
  
  const categoryMap = new Map<string, string>();
  
  for (const seed of seedFiles) {
    const category = await prisma.category.upsert({
      where: { name: seed.name },
      update: {},
      create: {
        name: seed.name,
        slug: seed.name.toLowerCase().replace(/\s+/g, '-'),
        description: `${seed.name} category`,
      },
    });
    
    categoryMap.set(seed.name, category.id);
    console.log(`   ✅ Category: ${seed.name}`);
  }
  
  console.log('');
  
  // Create products
  const createdProducts: Array<{ id: string; name: string; category: string }> = [];
  let productCodeCounter = 1;
  
  for (const { product, category } of allProducts) {
    const categoryId = categoryMap.get(category);
    if (!categoryId) continue;
    
    const price = product.selling_price || product.price || 0;
    const priceValue = typeof price === 'string' ? parseFloat(price) : price;
    
    const created = await prisma.product.create({
      data: {
        name: product.name,
        code: `PROD${String(productCodeCounter).padStart(6, '0')}`,
        category_id: categoryId,
        price: priceValue,
        quantity: product.quantity || 0,
        unit: product.unit || 'pcs',
        has_images: false,
      },
    });
    
    createdProducts.push({
      id: created.id,
      name: created.name,
      category: category,
    });
    
    productCodeCounter++;
  }
  
  console.log(`   ✅ Created ${createdProducts.length} products\n`);
  
  // Step 4: Match manual images to products
  console.log('🔄 Step 4: Matching Manual Images to Products...\n');
  console.log('   Strategy: Match images to products in order of upload date\n');
  console.log('   ⚠️  Note: Since images have random names, matching is sequential\n');
  console.log('   💡 You may need to manually verify and adjust matches\n');
  
  let matched = 0;
  let imageIndex = 0;
  
  // Group products by category to match better
  const productsByCategory = new Map<string, typeof createdProducts>();
  createdProducts.forEach(p => {
    if (!productsByCategory.has(p.category)) {
      productsByCategory.set(p.category, []);
    }
    productsByCategory.get(p.category)!.push(p);
  });
  
  // Match images to products sequentially
  for (const product of createdProducts) {
    if (imageIndex >= manualImages.length) {
      break;
    }
    
    const image = manualImages[imageIndex];
    
    try {
      // Check if product already has an image
      const existingImage = await prisma.productImage.findFirst({
        where: { product_id: product.id },
      });
      
      if (existingImage) {
        await prisma.productImage.update({
          where: { id: existingImage.id },
          data: {
            image: image.url,
            status: 'COMPLETE',
            is_active: true,
          },
        });
      } else {
        await prisma.productImage.create({
          data: {
            product_id: product.id,
            image: image.url,
            status: 'COMPLETE',
            is_active: true,
          },
        });
      }
      
      await prisma.product.update({
        where: { id: product.id },
        data: { has_images: true },
      });
      
      matched++;
      
      if (matched % 20 === 0) {
        console.log(`   Matched ${matched}/${Math.min(createdProducts.length, manualImages.length)} products...`);
      }
      
      imageIndex++;
    } catch (error) {
      console.error(`   ❌ Failed to match ${product.name}: ${(error as Error).message}`);
    }
  }
  
  console.log(`\n   ✅ Matched ${matched} products with manual images\n`);
  
  // Save mapping for review
  const mappingPath = path.resolve(__dirname, '../manual-image-mapping.json');
  const mapping = createdProducts.slice(0, matched).map((p, i) => ({
    productName: p.name,
    productCategory: p.category,
    imageUrl: manualImages[i]?.url || '',
    imageName: manualImages[i]?.name || '',
    uploadedAt: manualImages[i]?.uploadedAt || '',
  }));
  
  fs.writeFileSync(mappingPath, JSON.stringify({
    generatedAt: new Date().toISOString(),
    totalMatched: matched,
    mapping: mapping,
  }, null, 2));
  
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('📊 SUMMARY:');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`   ✅ Categories created: ${categoryMap.size}`);
  console.log(`   ✅ Products created: ${createdProducts.length}`);
  console.log(`   ✅ Images matched: ${matched}`);
  console.log(`   📸 Manual images available: ${manualImages.length}`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  
  console.log(`💾 Image mapping saved to: ${mappingPath}`);
  console.log('   Review this file to verify matches are correct\n');
  
  console.log('⚠️  IMPORTANT:');
  console.log('   Since images have random names, matches are sequential.');
  console.log('   Please review the mapping file and manually adjust if needed.\n');
  
  await prisma.$disconnect();
}

recreateAndMatchManualImages().catch((error) => {
  console.error('❌ Fatal error:', error);
  process.exit(1);
});
