import { prisma } from '../src/prisma/client';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';

dotenv.config();

interface ImageInfo {
  name: string;
  url: string;
  size?: number;
  format?: string;
  folder?: string;
  uploadedAt?: string;
}

// Check if image name looks auto-generated (random characters)
function isAutoGenerated(name: string): boolean {
  const parts = name.split('/');
  const fileName = parts[parts.length - 1];
  // Auto-generated names are typically random alphanumeric strings
  return fileName.length > 15 && /^[a-z0-9]+$/i.test(fileName) && !fileName.includes('_');
}

async function replaceWithFebMarImages() {
  console.log('🚀 Replacing product images with February/March 2026 images...\n');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  
  // Load images from JSON
  const jsonPath = path.resolve(__dirname, '../all-images-list.json');
  if (!fs.existsSync(jsonPath)) {
    console.error(`❌ JSON file not found: ${jsonPath}`);
    process.exit(1);
  }
  
  const jsonData = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  const allImages: ImageInfo[] = jsonData.cloudinary?.all || [];
  
  console.log(`📸 Loaded ${allImages.length} images from February/March 2026\n`);
  
  // Filter to auto-generated images (unused ones)
  const autoGeneratedImages = allImages.filter((img: ImageInfo) => {
    const imageName = img.name.split('/').pop() || '';
    return isAutoGenerated(imageName);
  });
  
  // Sort by upload date (most recent first)
  autoGeneratedImages.sort((a, b) => {
    const dateA = a.uploadedAt ? new Date(a.uploadedAt).getTime() : 0;
    const dateB = b.uploadedAt ? new Date(b.uploadedAt).getTime() : 0;
    return dateB - dateA;
  });
  
  console.log(`🤖 Found ${autoGeneratedImages.length} auto-generated images\n`);
  
  // Get all products with their current images
  const products = await prisma.product.findMany({
    select: {
      id: true,
      name: true,
      category: {
        select: { name: true },
      },
    },
    orderBy: [
      { category: { name: 'asc' } },
      { name: 'asc' },
    ],
  });
  
  const productsWithImages = await prisma.productImage.findMany({
    select: {
      product_id: true,
      image: true,
    },
  });
  
  const imageMap = new Map(productsWithImages.map(pi => [pi.product_id, pi.image]));
  
  console.log(`📦 Found ${products.length} products\n`);
  console.log('🔄 Matching auto-generated images to products...\n');
  console.log('📋 Strategy: Sequential 1:1 matching (sorted by category and name)\n');
  
  const matches: Array<{ productId: string; productName: string; categoryName: string; oldImage: string | null; newImage: string; imageName: string }> = [];
  let imageIndex = 0;
  
  for (const product of products) {
    if (imageIndex >= autoGeneratedImages.length) {
      break;
    }
    
    const image = autoGeneratedImages[imageIndex];
    const oldImage = imageMap.get(product.id) || null;
    
    matches.push({
      productId: product.id,
      productName: product.name,
      categoryName: product.category?.name || 'Uncategorized',
      oldImage: oldImage,
      newImage: image.url,
      imageName: image.name,
    });
    
    console.log(`✅ [${matches.length}/${Math.min(products.length, autoGeneratedImages.length)}] ${product.name} (${product.category?.name || 'Uncategorized'}) → ${image.name.split('/').pop()}`);
    
    imageIndex++;
  }
  
  console.log(`\n📊 Prepared ${matches.length} matches\n`);
  
  if (matches.length === 0) {
    console.log('⚠️  No matches to process. Exiting.');
    await prisma.$disconnect();
    return;
  }
  
  // Ask for confirmation (in a real scenario, but for now we'll proceed)
  console.log('💾 Updating database with new images...\n');
  
  let updated = 0;
  let failed = 0;
  
  for (const match of matches) {
    try {
      // Get existing image record
      const existingImage = await prisma.productImage.findFirst({
        where: { product_id: match.productId },
      });
      
      if (existingImage) {
        // Update existing image
        await prisma.productImage.update({
          where: { id: existingImage.id },
          data: {
            image: match.newImage,
            status: 'COMPLETE',
            is_active: true,
          },
        });
        updated++;
      } else {
        // Create new image record
        await prisma.productImage.create({
          data: {
            product_id: match.productId,
            image: match.newImage,
            status: 'COMPLETE',
            is_active: true,
          },
        });
        updated++;
      }
      
      // Update product has_images flag
      await prisma.product.update({
        where: { id: match.productId },
        data: { has_images: true },
      });
    } catch (error) {
      failed++;
      console.error(`❌ Failed to update ${match.productName}: ${(error as Error).message}`);
    }
  }
  
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('📊 SUMMARY:');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`   ✅ Updated: ${updated} products`);
  console.log(`   ❌ Failed: ${failed} products`);
  console.log(`   📈 Total processed: ${matches.length} products`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  
  // Save matches to file for review
  const matchesPath = path.resolve(__dirname, '../feb-mar-image-replacements.json');
  fs.writeFileSync(matchesPath, JSON.stringify({
    generatedAt: new Date().toISOString(),
    totalMatches: matches.length,
    matches: matches.map(m => ({
      productName: m.productName,
      category: m.categoryName,
      oldImage: m.oldImage,
      newImage: m.newImage,
      imageName: m.imageName,
    })),
  }, null, 2));
  
  console.log(`💾 Replacement details saved to: ${matchesPath}\n`);
  console.log('✅ Image replacement completed!\n');
  
  await prisma.$disconnect();
}

replaceWithFebMarImages().catch((error) => {
  console.error('❌ Fatal error:', error);
  process.exit(1);
});
