import { prisma } from '../src/prisma/client';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';

dotenv.config();

async function revertWrongMatches() {
  console.log('🔄 Reverting wrong image matches...\n');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  
  // Load the replacement file to see what was changed
  const replacementsPath = path.resolve(__dirname, '../feb-mar-image-replacements.json');
  let replacements: any = null;
  
  if (fs.existsSync(replacementsPath)) {
    replacements = JSON.parse(fs.readFileSync(replacementsPath, 'utf-8'));
    console.log(`📋 Found ${replacements.matches?.length || 0} replacements to review\n`);
  }
  
  // Get all products with images
  const productsWithImages = await prisma.productImage.findMany({
    include: {
      product: {
        select: {
          name: true,
          category: {
            select: { name: true },
          },
        },
      },
    },
  });
  
  console.log(`📦 Found ${productsWithImages.length} products with images\n`);
  
  // Identify auto-generated image URLs (those with random names)
  const autoGeneratedPattern = /\/[a-z0-9]{15,}\.(jpg|jpeg|png|webp)$/i;
  const wrongMatches: Array<{ productId: string; productName: string; imageUrl: string }> = [];
  
  for (const productImage of productsWithImages) {
    if (autoGeneratedPattern.test(productImage.image)) {
      wrongMatches.push({
        productId: productImage.product_id,
        productName: productImage.product?.name || 'Unknown',
        imageUrl: productImage.image,
      });
    }
  }
  
  console.log(`⚠️  Found ${wrongMatches.length} products with auto-generated image names\n`);
  
  if (wrongMatches.length === 0) {
    console.log('✅ No wrong matches found. All images appear to be correctly named.\n');
    await prisma.$disconnect();
    return;
  }
  
  console.log('📋 Products with potentially wrong images:\n');
  wrongMatches.slice(0, 20).forEach((match, i) => {
    console.log(`${i + 1}. ${match.productName}`);
    console.log(`   Image: ${match.imageUrl.split('/').pop()}\n`);
  });
  
  if (wrongMatches.length > 20) {
    console.log(`   ... and ${wrongMatches.length - 20} more\n`);
  }
  
  // Option 1: Remove images that are auto-generated (wrong matches)
  console.log('🗑️  Removing wrong image matches...\n');
  
  let removed = 0;
  let failed = 0;
  
  for (const match of wrongMatches) {
    try {
      // Find the product image record
      const productImage = await prisma.productImage.findFirst({
        where: { product_id: match.productId },
      });
      
      if (productImage && autoGeneratedPattern.test(productImage.image)) {
        // Delete the wrong image record
        await prisma.productImage.delete({
          where: { id: productImage.id },
        });
        
        // Update product has_images flag
        await prisma.product.update({
          where: { id: match.productId },
          data: { has_images: false },
        });
        
        removed++;
      }
    } catch (error) {
      failed++;
      console.error(`❌ Failed to remove image for ${match.productName}: ${(error as Error).message}`);
    }
  }
  
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('📊 SUMMARY:');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log(`   🗑️  Removed wrong images: ${removed} products`);
  console.log(`   ❌ Failed: ${failed} products`);
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  
  // Save list of products that need correct images
  const needsImagesPath = path.resolve(__dirname, '../products-needing-images.json');
  const productsNeedingImages = wrongMatches.map(m => ({
    productId: m.productId,
    productName: m.productName,
  }));
  
  fs.writeFileSync(needsImagesPath, JSON.stringify({
    generatedAt: new Date().toISOString(),
    total: productsNeedingImages.length,
    products: productsNeedingImages,
  }, null, 2));
  
  console.log(`💾 List of products needing correct images saved to: ${needsImagesPath}\n`);
  console.log('✅ Wrong image matches reverted!\n');
  console.log('📝 Next steps:');
  console.log('   1. Review the products-needing-images.json file');
  console.log('   2. Manually match images to products based on actual image content');
  console.log('   3. Or use a better matching strategy\n');
  
  await prisma.$disconnect();
}

revertWrongMatches().catch((error) => {
  console.error('❌ Fatal error:', error);
  process.exit(1);
});
